# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba882910ced6c879aedcb0295d0609c8375c707bc4599cdad9535d69c940a7aa4efc27fa187d101f91d6df7f0d84535a0a05811027d52dfbb11b26ed459e9e9c

test:
  secret_key_base: 829d1b8fb2267097f30f664536e212796e024361b1c9b006a46bbfae6a5743e38a345ed81bbd64910a3328a891ca11b380a478cd90eafd2208136037248598ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
